### PR TITLE
CSS-ified

### PR DESCRIPTION
**Pull request by BKFighter**
I remade it and added CSS but don't know PHP so you'll have to add that for me. :)

### CODE REVIEW

**Comment by haylinmoore** [comment]
Ok I connected the dots after many many minutes are yelling at my computer

**Comment by BKFighter** [comment]
Sorry I put you throguh such pain and suffering.

**Comment by haylinmoore** [comment]
no worry. It was more of me being stupid and messing things up

**Comment by BKFighter** [comment]
Ouch. I know how much that hurts... Speaking of which, so you know how I keep repeating that story about always disabling auto-run scripts when a page loads? Well, I still have a page thats too laggy to close...

**Comment by haylinmoore** [comment]
ok I will fix

**Comment by haylinmoore** [comment]
fixed @BKFighter

**Pull request closed without merging**
